config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  
  resources :lists do
    collection do
      get :cities
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :information_file, dependent: :destroy

  validates :name, :country, :city, :information_file, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :all_countries, only: [:new, :edit]
  before_action :set_message, only: [:show]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @cities = all_cities(@list.country)
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cities
    @cities = all_cities(params[:country])
    render :partial => "cities"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :country, :city, :information_file)
    end

    def all_countries
      @countries = CS.countries.map { |c| [c[1], c[0]] }
    end

    def all_cities(country_code)
      CS.states(country_code).keys.flat_map { |state| CS.cities(state, country_code) }
    end

    def set_message
      ip_country = Geocoder.search(remote_ip()).first.country
      if ip_country == @list.country
        @message = "Hello from #{country_name(ip_country)}"
      else
        @message = "HEEY It looks like you are from #{country_name(ip_country)}"
      end
    end

    def remote_ip
      if request.remote_ip == '127.0.0.1'
        # Hard coded remote address
        '119.155.29.195'
      else
        request.remote_ip
      end
    end

    def country_name(country_code)
      CS.countries[:"#{country_code}"]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper

  def file_link(information_file)
    link_to image_tag("/assets/no_image.png", width: "50", height: "50") + "Download", url_for(information_file), target: :_blank, class: "doc-img" if information_file.attached? 
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <br>
          <p id="notice"><%= notice %></p>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/lists/_cities.html.erb
<option >Select City *</option>
<%@cities.each do |city|%>
  <option value="<%= city %>"><%= city %></option>
<%end%>

app/views/lists/_form.html.erb
<div class="col-md-6">
  <%= form_with(model: list, local: true) do |form| %>
    <% if list.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

        <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :country %>
      <%= form.select :country, @countries, {}, { id: 'select_country', :class=>'chosen-select'} %>
    </div>

    <div class="form-group">
      <%= form.label :city %>
      <%= form.select :city, @cities ? @cities : [] , {}, id: 'select_city', :class=>'chosen-select' %>
    </div>

    <div class="form-group">
      <%= form.label :information_file %>
      <%= form.file_field :information_file, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-success' %>
      <%= link_to 'Back', lists_path, class: 'btn btn-dark' %>
    </div>
  <% end %>
</div>

<script type="text/javascript">

  $(function() {
    $('.chosen-select').chosen({
      allow_single_deselect: true,
      no_results_text: 'No results matched',
      width: "100%"
    });

  });

  $('#select_country').on('change', function(evt) {
    loadCities();
  });

  function loadCities(){
    $.ajax({
       url: '/lists/cities',
       data: {
        country: $("#select_country option:selected").val(),
        country_text: $("#select_country option:selected").text()
      },
      method: 'GET',
      success: function(data) {
       $('#select_city').empty();
       $('#select_city').append(data);
       $('#select_city').trigger("chosen:updated");

       }
    });
  }

</script>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

app/views/lists/index.html.erb
<div id="lists">
  <h1>Lists</h1>
  <span class="float-right">
    <%= link_to 'New List', new_list_path, class: 'btn btn-dark btn-sm' %>
  </span><br><br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Country</th>
        <th>City</th>
        <th>Information File</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% if @lists.any? %>
        <% @lists.each do |list| %>
          <tr>
            <td><%= list.id %></td>
            <td><%= list.name %></td>
            <td><%= list.country %></td>
            <td><%= list.city %></td>
            <td><%= file_link(list.information_file) %></td>

            <td><%= link_to 'Show', list, class: 'btn btn-primary btn-sm' %></td>
            <td><%= link_to 'Edit', edit_list_path(list), class: 'btn btn-primary btn-sm' %></td>
            <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
          </tr>
        <% end %>
      <% else %>
        <tr><td colspan="6"><p>No record found.</p></td></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<!-- <center><h1 border="1"> <%#= @message %></h1></center> -->
<div class="alert alert-dark" role="alert">
  <%= @message %>
</div>
<br>
<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @list.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @list.city %>
</p>

<p>
  <strong>Information File:</strong>
  <%= file_link(@list.information_file) %>
</p>

<%= link_to 'Edit', edit_list_path(@list), class: 'btn btn-primary btn-sm' %> 
<%= link_to 'Back', lists_path, class: 'btn btn-dark btn-sm' %>